server:
  port: 8082


# H2 DATABASE
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: pass
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        id:
          new_generator_mappings: false
    show-sql: true

  # SWAGGER RESOLVE PROBLEMS
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher